module.exports = {
	mode: 'development',
	entry: {
        'index' : './src/index.js',
  },
	module: {
		rules: [
			{
				test: [
					/\.css$/,
				],
				use: [
					{
						loader : 'typed-classnames-loader/classnames',
						// there are no options currently
					},
					{
						loader : 'style-loader',
						options : {
								sourceMap : true,
							},
					},
					{
						loader : 'typed-classnames-loader/type',
						options: {
							// change indent
							indent : {
								type : 'tab',
								size : 1,
							},
							// add custom banner
							banner : '// auto generated by typed-classnames-loader',
							// customize d.ts file
							template : (classNames, original) => {
								return `// there are ${classNames.length} classNames.\n${original}`;
							},
						},
					},
					{
						loader : 'css-loader',
						options : {
							// if set camelCase option to css-loader, typed-classnames-loader also generates them.
							camelCase: true,
							sourceMap : true,
							modules : true,
							localIdentName : '[hash:base64]',
						},
					},
				],
			},
		],
	},
};
